feature/improve forms
birotaio/fifteen-design-system-vue pull request #13
Opened 2022-06-22 21:16 UTC by arthur-bri

2022-06-24 10:17 UTC, qnp requested changes
- Redescendre d'un cran les divs des templates utilisant FField lorsque possible (_c.f._ commentaire sur le FRadio)

2022-06-24 10:17 UTC, qnp commented on components/form/FInput.vue
> +        slot(name="suffix")
On pourrait envisager que les slots "prefix" et "suffix" soient prévus de manière générique par FField et forwardé à ce dernier. Pas forcément nécessaire pour maintenant, à toi d'arbitrer

2022-06-24 10:17 UTC, qnp commented on components/form/FRadio.vue
> +      span.FRadio__labelText {{ label }}
On pourrait redescendre d'un cran :
```
FField.FRadio(
  :class="classes"
  :style="style"
  v-bind="..."
)
```

2022-06-24 10:17 UTC, qnp commented on composables/useFieldWithValidation.ts
> +        // Value is only used when validation in manual (eg. for custom inputs like FPhoneInput or FDigitsInput)
Oui, et dans ce cas la valeur passée `eventOrValue` est une value et pas un event et du coup pour moi la mécanique complexe derrière de récupération de la valeur qui se base sur l'event est inutile car tu fais un `await validate(value ?? fieldValue.value)` tu as ta valeur fieldValue.value déjà

2022-06-24 10:17 UTC, qnp commented on index.ts
> +export type { FRadioGroupProps } from '@/components/form/FRadioGroup.vue';
Peux-tu trier les `export type` de form de la même manière que tu as trié les `export` de composants de form ?

2022-06-24 10:17 UTC, qnp commented on components/form/FRadioGroup.vue
> +  )
regroupable également :
Le `FField`, au lieu de prendre `labelType` en props (qui a été oublié d'ailleurs ici), pourrait de façon plus haut niveau prendre `fieldset: boolean` en prop et i) se rendre comme un component :is fieldset et ii) calculer le label type corespondant

tu en penses quoi ?

2022-06-27 14:46 UTC, arthur-bri commented on components/form/FInput.vue
> +        slot(name="suffix")
Je ne vois pas trop comment ça pourrait se matérialiser, les `prefix` et `suffix` ne sont pas liés au FField selon moi mais aux input directement, non ? Je me dis que c'est plutôt à eux de porter les slots (d'ailleurs je ne vois pas trop comment faire sinon ?)

2022-06-28 08:43 UTC, merged