Develop w29 w30
birotaio/fifteen-design-system-vue pull request #26
Opened 2022-07-21 14:11 UTC by arthur-bri

2022-08-01 17:11 UTC, qnp requested changes

2022-08-01 17:11 UTC, qnp commented on config/icons/.utils.ts
> +  creditCardIconList.map(name => name as CreditCardTypeCardBrandId);
C'est peut-être naïf, mais :
```suggestion
const creditCardIconList: CreditCardTypeCardBrandId[] = [
  'american-express',
  'dinners-club',
  'discover',
  'elo',
  'jcb',
  'maestro',
  'mastercard',
  'unionpay',
  'visa',
];

export const getCreditCardIcons = () => creditCardIconList;
```

?

2022-08-01 17:11 UTC, qnp commented on config/icons/.utils.ts
> +  creditCardIconList.map(name => name as CreditCardTypeCardBrandId);
ça fonctionne ?

2022-08-01 17:11 UTC, qnp commented on stories/components/FsForm.vue
> +FForm.FForm(
la classe ici me semble redondante et inutile
```suggestion
FForm(
```

2022-08-01 17:11 UTC, qnp commented on stories/components/FsForm.vue
> +    FGridItem.FForm__actions(span="12")
Ton composant étant un composant pour storybook et nommé FsForm, alors la classe :
```suggestion
    FGridItem.FsForm__actions(span="12")
```

2022-08-02 09:43 UTC, arthur-bri commented on CHANGELOG.unreleased.md
> +- [FButton] Prevent button from being selected when loading
Oui c'est ça ! Je te propose de release une fois la PR review + je voulais avoir fait mes fixes sur les forms

2022-08-02 09:44 UTC, arthur-bri commented on components/FCreditCardIcon.vue
> +// TODO: dynamic import to reduce bundle size
Ah oui !

2022-08-02 09:45 UTC, arthur-bri commented on components/form/FCreditCardInput.vue
> +  rules: [isValidCreditCard],
Le merge des rules props / arguments de la composable est fait dans `useFieldWithValidation` :)

2022-08-02 09:51 UTC, arthur-bri commented on components/form/FForm.vue
> +const { values, validate, resetForm } = useForm({
Je pensais, et bien même pas finalement ! C'est le seul `reset*` exposé

2022-08-02 10:10 UTC, arthur-bri commented on config/icons/.utils.ts
> +  creditCardIconList.map(name => name as CreditCardTypeCardBrandId);
Oui ça fonctionne, et mieux que ça m'a fait voir une typo sur `dinners` ! Merci pour la proposition ;)

2022-08-02 10:16 UTC, arthur-bri commented on components/form/FCreditCardInput.vue
> +}
Je me suis trop avancé hier, il est précisé que ce n'est pas une lib de validation.

> This is not a validation library but rather a smaller component to help you build your own validation or UI library.

D'où la validation manuelle :)

2022-08-02 13:39 UTC, qnp approved these changes

2022-08-02 13:39 UTC, qnp commented on stories/components/FsForm.vue
> +      FButton(@click="() => reset()") Reset
ça ne fonctionne pas, simplement ça ?
```suggestion
      FButton(@click="reset") Reset
```

2022-08-02 13:43 UTC, arthur-bri commented on stories/components/FsForm.vue
> +      FButton(@click="() => reset()") Reset
Techniquement si, ça marche ! Mais avec une erreur TS : 
> Type '(state?: Partial<FormState<Record<string, unknown>>> | undefined) => void' is not assignable to type '(e: MouseEvent | KeyboardEvent) => any'.
>   Types of parameters 'state' and 'e' are incompatible.ts(2322)

Le reset prend un state en params mais le `FButton` emit l'event en passant l'event :/ 
C'est un petit contournement du TS mais je me dis finalement que ça évite tout problème de passer un event qui potentiellement aurait des champs en commun avec le state.

Qu'en penses-tu ?

2022-08-02 14:01 UTC, qnp commented on stories/components/FsForm.vue
> +      FButton(@click="() => reset()") Reset
Oui ok très bien ;-)

2022-08-02 14:01 UTC, merged