feature/expose focus event from form components
birotaio/fifteen-design-system-vue pull request #34
Opened 2022-08-08 15:56 UTC by arthur-bri

Closes SVC-4888

2022-08-08 16:15 UTC, qnp approved these changes
ça me semble bien, je ne comprends juste pas ce qui a été fait pour le FMenu, pourrais-tu m'expliquer ?

2022-08-09 12:17 UTC, qnp requested changes

2022-08-09 12:17 UTC, qnp commented on components/FMenu.vue
> +  if (isOpen.value) return;
je ne comprends pas ici, est-ce qu'on peut se call encore une fois ?

2022-08-09 12:17 UTC, qnp commented on components/form/FPhoneInput.vue
> +    :disabled="disabled"
j'ai plutôt tendance à mettre les évènements en bas après les props, (c'est d'ailleurs une bonne pratique)
```suggestion
    v-model="countryCode"
    width="100"
    :color="optionsMenuColor"
    :text-color="optionTextColor"
    :disabled="disabled"
    @toggle="newValue => (isMenuOpen = newValue)"
```

2022-08-09 12:17 UTC, qnp commented on components/form/FPhoneInput.vue
> +            @click="toggleMenu"
tbd

2022-08-09 12:17 UTC, qnp commented on components/form/FSelect.vue
> +    :disabled="disabled"
```suggestion
    :disabled="disabled"
    @toggle="newValue => (isMenuOpen = newValue)"
```

2022-08-09 12:17 UTC, qnp commented on components/form/FSelect.vue
> +        @keydown.enter="toggleMenu"
TBD

2022-08-09 12:27 UTC, qnp requested changes

2022-08-09 12:27 UTC, qnp commented on components/FMenu.vue
> +watch(isOpen, newValue => emit('toggle', newValue), { immediate: true });
```suggestion
watch(isOpen, value => emit('toggle', value), { immediate: true });
```

2022-08-09 12:27 UTC, qnp commented on components/form/FPhoneInput.vue
> +    @toggle="newValue => (isMenuOpen = newValue)"
```suggestion
    @toggle="value => (isMenuOpen = value)"
```

2022-08-09 12:27 UTC, qnp commented on components/form/FSelect.vue
> +    @toggle="newValue => (isMenuOpen = newValue)"
```suggestion
    @toggle="value => (isMenuOpen = value)"
```

2022-08-09 12:33 UTC, arthur-bri commented on components/FMenu.vue
>  function toggleMenu() {
Il y en a bien une sur le dernier commit, curieux 🤔

2022-08-11 09:35 UTC, qnp approved these changes

2022-08-11 09:55 UTC, merged