Develop w23 w24
birotaio/fifteen-design-system-vue pull request #5
Opened 2022-06-10 17:32 UTC by arthur-bri

2022-06-24 09:53 UTC, qnp requested changes

2022-06-24 09:53 UTC, qnp commented on composables/useFieldWithValidation.ts
> +    shouldValidate?: boolean | undefined
```suggestion
    shouldValidate?: boolean
```

2022-06-24 09:53 UTC, qnp commented on stories/FForm.stories.ts
> +});
Pour moi ça c'est un bon candidat à un composant monofichier séparé dans `stories/components` importé tel quel ici, ça rendrait plus facile la lecture du template ! ;-)

2022-06-25 10:33 UTC, qnp requested changes

2022-06-25 10:33 UTC, qnp commented on rules/index.ts
> +export { mask } from './mask';
Ça fonctionne de faire ça simplement ?

pour moi :
- j'aurai tendance à dire que Vite ne build pas ce fichier parce qu'inconnu dans l'`entry` qui est `index.ts` de la racine.
- lors d'un npm install du package, les fichiers dans /rules ne doivent pas être pris en compte. Il doivent être précisés dans `"files"` dans le `package.json` (mais ici ils ne sont pas build)

Le fait qu'ils ne soient pas build n'est peut-être pas un problème en soi, puisqu'on forward des sources et qu'on est en ESM.

[[ Sujet un peu relié mais délicat, en tout cas c'est la même chose les `resolvers` ne sont pas build, et Storybook (du corpo) crash parce qu'ils sont en ESM ]]

2022-06-25 14:15 UTC, qnp commented on rules/index.ts
> +export { mask } from './mask';
*UPDATE* sur ce sujet.
J'ai mis en place un build propre de la lib en ESM et CJS. J'ai rajouté un script qui build les resolvers. Je pense qu'il s'agirait de faire ça pour les rules si jamais le besoin se présente
https://github.com/birotaio/fifteen-design-system-vue/pull/14

2022-06-27 16:49 UTC, arthur-bri commented on components/FDigitsInput.vue
> +  setTimeout(() => {
`nextTick` en effet c'est la première option tentée mais ça n'a eu aucun effet.
Il faut defer le comportement natif de l'input ce qui est assez peu commun je pense. Et je trouve que de `prevent` (qui est l'autre option) amène à une logique plus lourde...

2022-06-27 16:58 UTC, arthur-bri commented on components/FSelect.vue
>      event.stopPropagation();
Oui bonne idée !

2022-06-27 17:00 UTC, arthur-bri commented on components/FSelect.vue
>      event.stopPropagation();
Non pas bonne idée finalement > Le `stopPropagation` est conditionné, on ne veut pas stop la propagation (en l'occurence _prevent_ l'ouverture du menu) dans tous les cas :)

2022-06-27 17:18 UTC, arthur-bri commented on components/FMenu.vue
> +const isOpen = useVModelProxy(props, 'isOpen', emit);
J'ADORE ! 😄

2022-06-27 17:28 UTC, arthur-bri commented on components/FFieldLabel.vue
> +  :for="type === 'label' ? name : null"
Le `null` et `undefined` ne rendent pas l'attribut. Après vérification, seule la `''` rend l'attribut (sans valeur donc) :)

2022-06-28 06:16 UTC, arthur-bri commented on components/FFieldHint.vue
> +  top 100%
Repris sur la #13

2022-06-28 06:26 UTC, qnp commented on components/FDigitsInput.vue
> +  setTimeout(() => {
Ok, ça me va alors ^^

2022-06-28 06:27 UTC, qnp commented on components/FSelect.vue
>      event.stopPropagation();
Ah oui ok !

2022-06-28 08:39 UTC, arthur-bri commented on rules/index.ts
> +export { mask } from './mask';
Vu ensemble, parfait merci :)

2022-06-30 09:43 UTC, qnp approved these changes

2022-06-30 09:44 UTC, merged